export default [
    {
        id: 1,
        title: "Allure",
        description: "A sophisticated fragrance with hints of citrus and musk.",
        price: 45.99,
        rating: 4.5,
        stock: 75,
        brand: "Calvin Klein",
        category: ["men","new"],
        thumbnail: "perfume1.png",
        images: []
    },
    {
        id: 2,
        title: "Chance",
        description: "A floral and woody scent perfect for everyday wear.",
        price: 59.95,
        rating: 4.2,
        stock: 110,
        brand: "Chanel",
        category: ["women"],
        thumbnail: "perfume2.png",
        images: []
    },
    {
        id: 3,
        title: "Rouge",
        description: "A refreshing scent with aquatic and green notes.",
        price: 32.50,
        rating: 4.0,
        stock: 92,
        brand: "Dior",
        category: ["women" , "men"],
        thumbnail: "perfume3.png",
        images: []
    },
    {
        id: 4,
        title: "Shalimar",
        description: "An elegant fragrance blending floral and spicy essences.",
        price: 68.00,
        rating: 4.7,
        stock: 85,
        brand: "Giorgio Armani",
        category: ["women"],
        thumbnail: "perfume4.png",
        images: []
    },
    {
        id: 5,
        title: "Fiand",
        description: "A bold and captivating scent with leather and amber tones.",
        price: 90.25,
        rating: 4.9,
        stock: 78,
        brand: "Hugo Boss",
        category: ["men"],
        thumbnail: "perfume5.png",
        images: []
    },
    {
        id: 6,
        title: "Dior",
        description: "A warm and sensual fragrance with vanilla and spice.",
        price: 55.00,
        rating: 4.3,
        stock: 100,
        brand: "Jean Paul Gaultier",
        category: ["women"],
        thumbnail: "perfume6.png",
        images: []
    },
    {
        id: 7,
        title: "Fahrenheit",
        description: "An oriental fragrance with spicy and amber notes.",
        price: 75.50,
        rating: 4.8,
        stock: 88,
        brand: "Tom Ford",
        category: ["women" , "men"],
        thumbnail: "perfume7.png",
        images: []
    },
    {
        id: 8,
        title: "Perfume 8",
        description: "A vibrant and fresh scent with floral and fruity notes.",
        price: 55.00,
        rating: 4.6,
        stock: 95,
        brand: "Dolce & Gabbana",
        category: ["women"],
        thumbnail: "perfume5.png",
        images: []
    },
    {
        id: 9,
        title: "Perfume 9",
        description: "An invigorating scent with hints of mint and cedarwood.",
        price: 48.75,
        rating: 4.4,
        stock: 82,
        brand: "Paco Rabanne",
        category: ["men"],
        thumbnail: "perfume4.png",
        images: []
    },
    {
        id: 10,
        title: "Perfume 10",
        description: "A luxurious fragrance with floral and woody undertones.",
        price: 78.99,
        rating: 4.9,
        stock: 70,
        brand: "Gucci",
        category: ["women"],
        thumbnail: "perfume1.png",
        images: []
    },
    {
        id: 11,
        title: "Perfume 11",
        description: "A charismatic and bold scent with leather and spice.",
        price: 63.50,
        rating: 4.7,
        stock: 88,
        brand: "Versace",
        category: ["men"],
        thumbnail: "perfume3.png",
        images: []
    },
    {
        id: 12,
        title: "Perfume 12",
        description: "A delicate and romantic fragrance with floral and musk.",
        price: 42.25,
        rating: 4.3,
        stock: 105,
        brand: "Yves Saint Laurent",
        category: ["women"],
        thumbnail: "perfume4.png",
        images: []
    },
    {
        id: 13,
        title: "Perfume 13",
        description: "An intense and sophisticated scent with amber and oud.",
        price: 92.00,
        rating: 4.8,
        stock: 65,
        brand: "Givenchy",
        category: ["women" , "men"],
        thumbnail: "perfume7.png",
        images: []
    },
    {
        id: 14,
        title: "Perfume 14",
        description: "A mysterious and sensual fragrance with vanilla and patchouli.",
        price: 57.75,
        rating: 4.5,
        stock: 80,
        brand: "Burberry",
        category: ["men"],
        thumbnail: "perfume6.png",
        images: []
    }
]